# version: '3.1'

# services:
# mysql server: mysql
# mysql:
#   image: mysql
#   command: --default-authentication-plugin=mysql_native_password
#   restart: always
#   platform: linux/amd64
#   environment:
#     MYSQL_ROOT_PASSWORD: 123

# adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 8080:8080

# postgres server: postgres

# postgres:
#   image: postgres
#   restart: always
#   platform: linux/amd64
#   environment:
#     POSTGRES_PASSWORD: 123

# mongo:
#   image: mongo
#   restart: always
#   environment:
#     MONGO_INITDB_ROOT_USERNAME: root
#     MONGO_INITDB_ROOT_PASSWORD: 123

# mongo-express:
#   image: mongo-express
#   restart: always
#   ports:
#     - 8081:8081
#   environment:
#     ME_CONFIG_MONGODB_ADMINUSERNAME: root
#     ME_CONFIG_MONGODB_ADMINPASSWORD: 123
#     ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/
